name: Typecheck PR

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: pnpm

      - name: Instalar dependências
        run: pnpm install

      - name: Executar typecheck
        run: pnpm typecheck
